name: Continuous Integration
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  get-previous-tag:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - run: |
         true
